version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.5.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          alpha-version-ref: 'dev:$CIRCLE_BRANCH'
          checkout: true
          orb-name: fauxalgore/playground
          requires:
            - orb-tools/lint
