
version: 2.1

description: |
  Sandbox for prototyping orbs


commands:
  setbashenv:
    description: "Copy the bash_env from the first job so that TERMINUS_ENV persists."
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - run: cp /tmp/workspace/bash_env.txt $BASH_ENV

jobs:
  backstop:
    docker:
    - image: backstopjs/backstopjs:3.9.5
    steps:
    - setbashenv
    - run: backstop reference --config=backstop/backstop-config.js
    - run: backstop test --config=backstop/backstop-config.js || echo "backstop failed but this message suppresses a failure of the entire script. The reporting script will detect the fail"
    - store_artifacts:
        path: backstop_data

    - run:
        name: Report
        command: |
              CIRCLE_ARTIFACTS_URL=${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/root/project
              IMAGE=$(find -- backstop_data/bitmaps_test -type f -name "*.png" | head -n 1)
              REPORT_URL=${CIRCLE_ARTIFACTS_URL}/backstop_data/html_report/index.html
              BODY="### Visual regression report:\\n\\n[![Visual report](${CIRCLE_ARTIFACTS_URL}/${IMAGE})]($REPORT_URL)"
              {
                GITHUB_URL="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commits/${CIRCLE_SHA1}/comments?access_token=${GITHUB_TOKEN}"
                curl -d '{ "body": "'"${BODY}"'" }' -X POST "${GITHUB_URL}"
              } &> /dev/null
